name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job  was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/schlesingergroup/Demo'
          azure-pipeline-name: 'Telmy Test Release Pipeline' # name of the Azure pipeline to be triggered
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
      - run: echo "ğŸ This job's status is ${{ job.status }}."
